#!/bin/sh

NAME=lvshell
PIDFILE=/var/run/$NAME.pid

case "$1" in
	start)
		printf "Starting $NAME: "
		start-stop-daemon --start --quiet --background --exec /usr/bin/lvshell \
		&& echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping $NAME: "
		start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		&& echo "OK" || echo "FAIL"
		;;
	*)
		echo "usage: $0 {start|stop}"
		;;
esac
exit 0
